import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

/**
 * Next.js Middleware
 *
 * Sets a dynamic Content-Security-Policy header on every page response.
 * CSP is handled here (rather than in next.config.mjs static headers)
 * so it can be extended with per-request values in the future.
 *
 * All other security headers (HSTS, X-Frame-Options, etc.) remain in
 * next.config.mjs static headers.
 */

export function middleware(request: NextRequest) {
  // Generate a cryptographically random nonce for this request.
  // Next.js reads the CSP from the *request* headers, extracts the nonce
  // via the 'nonce-{value}' pattern, and automatically applies it to:
  //   - Framework scripts (React, Next.js runtime)
  //   - Page-specific JavaScript bundles
  //   - Inline styles and scripts generated by Next.js
  // This allows us to use 'strict-dynamic' and avoid 'unsafe-inline'.
  const nonce = Buffer.from(crypto.randomUUID()).toString('base64')
  const isDev = process.env.NODE_ENV === 'development'

  const csp = [
    "default-src 'self'",
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'${isDev ? " 'unsafe-eval'" : ''} https://js.stripe.com https://m.stripe.network https://va.vercel-scripts.com`,
    "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://api.x.ai https://api.stripe.com https://api.resend.com https://hooks.slack.com https://*.upstash.io https://vitals.vercel-insights.com https://lottie.host https://*.lottiefiles.com https://cdn.jsdelivr.net https://unpkg.com",
    "img-src 'self' data: blob: https://*.supabase.co https://*.stripe.com https://lottie.host https://res.cloudinary.com",
    `style-src 'self' 'nonce-${nonce}' https://fonts.googleapis.com`,
    "font-src 'self' data: https://fonts.gstatic.com",
    "frame-src 'self' https://js.stripe.com https://hooks.stripe.com",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ].join('; ')

  const requestHeaders = new Headers(request.headers)
  requestHeaders.set('x-nonce', nonce)
  requestHeaders.set('Content-Security-Policy', csp)

  const response = NextResponse.next({
    request: { headers: requestHeaders },
  })

  response.headers.set('Content-Security-Policy', csp)

  return response
}

// Run middleware on all routes except static files and images
export const config = {
  matcher: [
    /*
     * Match all request paths except:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico, icon.png, apple-icon.png (metadata files)
     * - manifest.json, robots.txt, sitemap.xml (SEO files)
     * - .svg, .png, .jpg, .jpeg, .gif, .webp (image files)
     */
    {
      source:
        '/((?!_next/static|_next/image|favicon\\.ico|icon\\.png|apple-icon\\.png|manifest\\.json|robots\\.txt|sitemap\\.xml|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
      missing: [
        { type: 'header', key: 'next-router-prefetch' },
        { type: 'header', key: 'purpose', value: 'prefetch' },
      ],
    },
  ],
}
